apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flink-job-service-monitor
  labels:
    release: prometheus
spec:
  endpoints:
    - interval: 5s
      path: /metrics
      port: "metrics"
      scheme: http
  namespaceSelector:
    matchNames:
      - flink-demo
  selector:
    matchLabels:
      app: flink-session-job-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flink-task-service-monitor
  labels:
    release: prometheus
spec:
  endpoints:
    - interval: 5s
      path: /metrics
      port: "metrics"
      scheme: http
  namespaceSelector:
    matchNames:
      - flink-demo
  selector:
    matchLabels:
      app: flink-session-task-metrics