{
 "title": "Flink Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ERROR Occured",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_error_handling_demo_error_counter > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_error_handling_demo_error_counter)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_error_handling_demo_success_counter)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(flink_jobmanager_numRunningJobs)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Summary",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_error_handling_demo_error_counter",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}