apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-datasource
spec:
  valuesFrom:
    - targetPath: "secureJsonData.httpHeaderValue1"
      valueFrom:
        secretKeyRef:
          name: "grafana-datasource-prometheus"
          key: "token"
  datasource:
    name: Prometheus
    type: prometheus
    access: proxy
    url: https://thanos-querier.openshift-monitoring.svc:9091
    isDefault: true
    jsonData:
      httpHeaderName1: "Authorization"
      tlsSkipVerify: true
    secureJsonData:
      httpHeaderValue1: >-
        Bearer $token
  instanceSelector:
    matchLabels:
      dashboards: grafana