apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana
spec:
  path: /
  to:
    name: grafana-service
    weight: 100
    kind: Service
  host: ''
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  port:
    targetPort: grafana
  alternateBackends: []