apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-prometheus-reader
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/api", "/api/v1/query", "/api/v1/query_range", "/api/v1/series", "/federate", "/api/v1/label"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-prometheus-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-prometheus-reader
subjects:
- kind: ServiceAccount
  name: grafana-serviceaccount
  namespace: flink-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-prometheus-read
  namespace: openshift-monitoring
subjects:
  - kind: ServiceAccount
    name: grafana-serviceaccount
    namespace: flink-demo
roleRef:
  kind: ClusterRole
  name: prometheus-k8s
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-serviceaccount-token
  annotations:
    kubernetes.io/service-account.name: grafana-serviceaccount
type: kubernetes.io/service-account-token