FROM docker.io/flink:1.20-java17

USER root

RUN mkdir -p /opt/flink/demo

COPY target/kafka-aggregator-flink-1.0.jar /opt/flink/demo/
                                        
RUN chgrp -R 0 /opt/flink && \ 
    chmod -R g=u /opt/flink

USER 1001