FROM docker.io/flink:1.20-java17

USER root

RUN mkdir -p /opt/flink/plugins/s3-fs-presto
RUN mkdir -p /opt/flink/demo

RUN curl -sL https://repo1.maven.org/maven2/org/apache/flink/flink-s3-fs-presto/1.20.0/flink-s3-fs-presto-1.20.0.jar \
    -o /opt/flink/plugins/s3-fs-presto/flink-s3-fs-presto-1.20.0.jar

COPY target/kafka-aggregator-flink-1.0.jar /opt/flink/demo/
                                        
RUN chgrp -R 0 /opt/flink && \ 
    chmod -R g=u /opt/flink

USER 1001