apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: flink-cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
  namespace: flink-demo
spec:
  kafka:
    authorization:
      type: simple
    version: 4.0.0
    metadataVersion: 4.0-IV3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: flink-cluster-controllers
  labels:
    strimzi.io/cluster: flink-cluster
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: ephemeral
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: flink-cluster-brokers
  labels:
    strimzi.io/cluster: flink-cluster
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: ephemeral
