apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink-job-submitter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink-job-submitter-role
rules:
  - apiGroups: ["flink.apache.org"]
    resources: ["flinksessionjobs"]
    verbs: ["create", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-job-submitter-binding
subjects:
  - kind: ServiceAccount
    name: flink-job-submitter
roleRef:
  kind: Role
  name: flink-job-submitter-role
  apiGroup: rbac.authorization.k8s.io